# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    autowire: true

  app.url_repository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\Url

  app.url_data_access:
      class: AppBundle\Lib\DAL\Doctrine\UrlDal
      arguments:
          - "@app.url_repository"
          - "@doctrine.orm.entity_manager"

  app.web_surfer_service:
      class: AppBundle\Service\WebSurfer\WebSurferService
      arguments:
          - "@app.url_data_access"
          - "@form.factory"
          - "@validator"
          - "@app.web_surfer_cookie"

  app.web_surfer_cookie:
      class: AppBundle\Service\WebSurfer\UrlCookie

  app.url_filter_service:
      class: AppBundle\Service\UrlFilterService
      arguments:
          - "@app.url_data_access"
          - "@form.factory"

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
